services:
  frontend:
    image: frontend:latest
    build: ./frontend/frontend
    ports: 
    - "3000:80"
    depends_on:
      - backend

  backend:
    image: backend:latest
    build: ./backend
    ports: 
    - "5000:5000"
    volumes:
      - ~/.google/credentials/google_credentials.json:/home/maksi/.google/credentials/google_credentials.json
    environment:
      projectID: "marine-catfish-310009" # to change
      DatasetID: "pipeline_dataset_terraform" 